// Generated by CoffeeScript 1.3.1
(function() {
  var notification;

  chrome.extension.onRequest.addListener(function(request, sender, callback) {
    if (request.action === 'notification') {
      return notification(request.image, request.title, request.message);
    }
  });

  notification = function(image, title, message) {
    notification = window.webkitNotifications.createNotification(image, title, message);
    return notification.show();
  };

}).call(this);
