// Generated by CoffeeScript 1.3.1
(function() {
  var fetch_feeds;

  fetch_feeds = function() {
    debugger;    return jQuery('.fbGroupsStream li');
  };

  $(document).ready(function() {
    console.log('hi');
    return fetch_feeds();
  });

}).call(this);
