// Generated by CoffeeScript 1.3.1
(function() {
  var add_player_box, fetch_feeds, get_youtube_id, play, queue_songs;

  window.GoyakaPlayer = {};

  window.GoyakaPlayer.songs = [];

  fetch_feeds = function() {
    var feed, feeds, link, song, song_item, _i, _len, _results;
    feeds = jQuery('.fbGroupsStream li.uiUnifiedStory');
    _results = [];
    for (_i = 0, _len = feeds.length; _i < _len; _i++) {
      feed = feeds[_i];
      link = jQuery(feed).find('.uiAttachmentTitle a');
      if (link.length > 0) {
        song = $(link[0]);
        song_item = {
          'song': song.html(),
          'url': song.attr('href')
        };
        _results.push(window.GoyakaPlayer.songs.push(song_item));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  get_youtube_id = function(url) {
    var matches, regex_pattern;
    regex_pattern = /.*v=([^&.]*)/;
    matches = regex_pattern.exec(url);
    if (matches.length > 1) {
      return matches[1];
    } else {
      return false;
    }
  };

  add_player_box = function() {
    var atts, first_youtube_id, params, player_wrap;
    player_wrap = jQuery('<div style="padding:3px; border:1px solid #000; border-radius:4px;position:absolute;top:100px;left:20%;background-color:#fff;zoom:2;z-index:99999999;"><div id="goyakatube"></div></div>');
    jQuery('body').append(player_wrap);
    params = {
      allowScriptAccess: "always"
    };
    atts = {
      id: "goyakaplayer"
    };
    first_youtube_id = get_youtube_id(window.GoyakaPlayer.songs[0]['url']);
    return swfobject.embedSWF("https://www.youtube.com/v/" + first_youtube_id + "?enablejsapi=1&playerapiid=ytplayer&version=3", "goyakatube", "250", "180", "8", null, null, params, atts);
  };

  queue_songs = function() {
    var player, song, songs_list, _i, _len, _results;
    player = document.getElementById('goyakaplayer');
    songs_list = window.GoyakaPlayer.songs.slice(1, window.GoyakaPlayer.songs.length);
    _results = [];
    for (_i = 0, _len = songs_list.length; _i < _len; _i++) {
      song = songs_list[_i];
      console.log('Queueing ' + song['song']);
      _results.push(player.cueVideoByUrl(song['url']));
    }
    return _results;
  };

  play = function() {
    var player;
    player = document.getElementById('goyakaplayer');
    return player.playVideo();
  };

  jQuery(document).ready(function() {
    fetch_feeds();
    add_player_box();
    queue_songs();
    return play();
  });

}).call(this);
