// Generated by CoffeeScript 1.3.1
(function() {
  var GoyakaPlayer, get_youtube_id, is_player_loaded, notifySong, playNext, playSong, pollPlayerState;

  window.GoyakaPlayer = GoyakaPlayer = {};

  window.GoyakaPlayer.currentPlayId = 0;

  window.GoyakaPlayer.songs = [];

  GoyakaPlayer.STOPPED = 0;

  window.GoyakaPlayer.fetch_feeds = function() {
    var actor_image, actor_name, feed, feeds, link, message, song, song_item, _i, _len, _results;
    feeds = jQuery('.fbGroupsStream li.uiUnifiedStory');
    _results = [];
    for (_i = 0, _len = feeds.length; _i < _len; _i++) {
      feed = feeds[_i];
      link = jQuery(feed).find('.uiAttachmentTitle a');
      if (link.length > 0) {
        actor_image = jQuery(feed).find('.actorPhoto img').attr('src');
        actor_name = jQuery(feed).find('.actorName a').html();
        message = jQuery(feed).find('.messageBody').html();
        song = $(link[0]);
        song_item = {
          actor_image: actor_image,
          actor_name: actor_name,
          message: message,
          song: song.find('span').html(),
          url: song.attr('href')
        };
        _results.push(window.GoyakaPlayer.songs.push(song_item));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  get_youtube_id = function(url) {
    var matches, regex_pattern;
    regex_pattern = /.*v=([^&.]*)/;
    matches = regex_pattern.exec(url);
    if (matches.length > 1) {
      return matches[1];
    } else {
      return false;
    }
  };

  window.GoyakaPlayer.add_player_listeners = function() {
    if (is_player_loaded()) {
      return window.setInterval(pollPlayerState, 5000);
    } else {
      return window.setTimeout(window.GoyakaPlayer.add_player_listeners, 10000);
    }
  };

  playNext = function() {
    console.log('Playing next song');
    window.GoyakaPlayer.currentPlayId = window.GoyakaPlayer.currentPlayId + 1;
    return playSong(window.GoyakaPlayer.currentPlayId);
  };

  pollPlayerState = function() {
    var player, player_state;
    player = document.getElementById('goyakaplayer');
    player_state = player.getPlayerState();
    if (player_state === GoyakaPlayer.STOPPED) {
      return playNext();
    }
  };

  window.GoyakaPlayer.add_player_box = function() {
    var atts, first_youtube_id, params, player_wrap;
    player_wrap = jQuery('<div style="padding:2px; border:1px solid #333; border-radius:3px;position:fixed;bottom:-7px;left:20%;background-color:#fff;zoom:2;z-index:99999999;"><div id="goyakatube"></div></div>');
    jQuery('body').append(player_wrap);
    params = {
      allowScriptAccess: "always"
    };
    atts = {
      id: "goyakaplayer"
    };
    first_youtube_id = get_youtube_id(window.GoyakaPlayer.songs[0]['url']);
    swfobject.embedSWF("https://www.youtube.com/v/" + first_youtube_id + "?enablejsapi=1&playerapiid=ytplayer&version=3", "goyakatube", "150", "80", "8", null, null, params, atts);
    return window.GoyakaPlayer.add_player_listeners();
  };

  is_player_loaded = function() {
    if (document.getElementById('goyakaplayer')) {
      return true;
    } else {
      return false;
    }
  };

  notifySong = function(id) {
    var song, text;
    song = window.GoyakaPlayer.songs[id];
    text = song['actor_name'] + ' ' + song['message'];
    return chrome.extension.sendRequest({
      action: 'notification',
      image: song['actor_image'],
      title: song['actor_name'],
      message: song['message']
    });
  };

  playSong = function(id) {
    var player, youtube_id;
    player = document.getElementById('goyakaplayer');
    youtube_id = get_youtube_id(window.GoyakaPlayer.songs[id]['url']);
    player.cueVideoById(youtube_id);
    player.playVideo();
    return notifySong(id);
  };

  window.GoyakaPlayer.play = function() {
    if (is_player_loaded()) {
      return playSong(0);
    } else {
      return window.setTimeout(window.GoyakaPlayer.play, 5000);
    }
  };

}).call(this);
