// Generated by CoffeeScript 1.3.1
(function() {

  jQuery(document).ready(function() {
    GoyakaPlayer.fetch_feeds();
    GoyakaPlayer.add_player_box();
    return GoyakaPlayer.play();
  });

}).call(this);
